version: '3.5'

networks:
  eks-net:
    driver: bridge

volumes:
    tfdata_vol:
    localstack_vol:   

services:

  localstack: 
    image: localstack/localstack-pro
    container_name: localstack-container
    env_file:
      - .env
    environment:
      - SERVICES=iam,sts,cloudwatch,apigateway,dynamodb,lambda,route53 
      - DEBUG=3
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      # use this flag if PRO token is not available
      - ACTIVATE_PRO=0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    networks: 
      - eks-net
    volumes:
      - localstack_vol:/var/lib/localstack/
      - "/var/run/docker.sock:/var/run/docker.sock"
   


  terraform-container:
    # image tag isused to bind to a specific version of terraform
    image: hashicorp/terraform:1.8.0
    container_name: terraform
    networks:
      - eks-net
    volumes:
      - tfdata_vol:/tfdata
      - ./infrastructure:/infrastructure
      - ./code:/code
    working_dir: /infrastructure
    environment:
      - TF_DATA_DIR=/tfdata
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}