version: '3.5'

volumes:
    tfdata_vol:

services:
  tf:
    # image tag isused to bind to a specific version of terraform
    image: hashicorp/terraform:1.8
    container_name: terraform
    volumes:
      - tfdata_vol:/tfdata
      - ./infrastructure:/infrastructure
    working_dir: /infrastructure
    environment:
      - TF_DATA_DIR=/tfdata